site_name: Datascience Projects
site_url: https://squidfunk.github.io/smrenato/datascience-projects/
site_author: Renato
site_description: >-
  A collection of datascience projects

# Repository
repo_name: smrenato/datascience-projects
repo_url: https://github.com/smrenato/datascience-projects

theme:
  name: material

  palette:
  
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-2
        name: Switch to light mode

    - scheme: default
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-5
        name: Switch to dark mode

  icon:
    repo: fontawesome/brands/github-alt

# markdown_extensions:
#   - pymdownx.emoji
#   - pymdownx.tasklist
#   - pymdownx.mark
#   - pymdownx.tilde
#   - pymdownx.highlight
#   - pymdownx.superfences